2020-06-16 01:06:08,478 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 2281197ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 04:33:58,039 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 12429539ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 04:39:39,758 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 04:45:01,494 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301713ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 04:50:43,180 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 04:56:24,888 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 05:02:06,612 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301694ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 05:07:28,353 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301728ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 06:55:44,332 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 6455953ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 07:01:26,070 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301707ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 07:29:34,714 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301691ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 09:10:11,517 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 6016779ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 09:26:14,096 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 942538ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 09:41:27,066 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 872913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 09:46:37,148 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 250042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 20:00:14,695 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 36797503ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 20:02:47,166 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 152465ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 20:17:38,638 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 891462ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 20:32:47,756 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 909114ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 21:11:16,567 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 2308748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-16 22:34:23,081 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 4986511ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:01:39,681 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 435571ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:07:01,376 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:12:43,090 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301696ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:18:24,817 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301707ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:24:06,525 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301681ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 00:29:28,224 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:05:23,602 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 2115360ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:11:05,321 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:16:47,043 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301694ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:22:08,757 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301686ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:27:50,511 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301739ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:33:32,261 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301729ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 01:39:13,970 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301680ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 03:27:09,750 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 6455760ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 03:44:14,926 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301718ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 03:49:36,986 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 302039ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 03:55:18,697 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301685ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 04:01:00,405 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 05:49:15,689 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 6455263ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 05:54:57,426 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301700ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 06:00:19,153 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301708ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 06:06:00,920 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301743ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 06:11:42,626 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301688ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 06:17:04,987 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 302338ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 06:22:46,721 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301713ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 07:49:58,797 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 5192057ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:06:00,654 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:11:42,374 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301702ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:13:10,037 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 67644ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:18:31,678 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 301632ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:21:38,337 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 166645ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 08:39:01,203 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 1042837ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 11:49:30,525 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 11409219ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 11:54:36,215 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 305651ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 13:08:29,251 ERROR 1862 nodejs.ClusterClientNoResponseError: client no response in 4433017ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1862
hostname: 192.168.0.115

2020-06-17 13:31:30,296 ERROR 9107 [egg-mongoose] mongodb://127.0.0.1:27017/yuechen disconnected
2020-06-17 13:31:30,297 ERROR 9107 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9107
hostname: wangdeMacBook-Pro.local

2020-06-17 13:31:30,299 ERROR 9107 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9107
hostname: wangdeMacBook-Pro.local

2020-06-17 13:31:30,301 ERROR 9107 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9107
hostname: wangdeMacBook-Pro.local

2020-06-17 13:33:29,844 ERROR 9154 [egg-mongoose] mongodb://127.0.0.1:27017/yuechen disconnected
2020-06-17 13:33:29,845 ERROR 9154 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9154
hostname: wangdeMacBook-Pro.local

2020-06-17 13:33:29,846 ERROR 9154 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9154
hostname: wangdeMacBook-Pro.local

2020-06-17 13:33:29,847 ERROR 9154 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:310:20)
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/wangjiang/code/yuechen/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 9154
hostname: wangdeMacBook-Pro.local

2020-06-17 16:48:02,751 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 10993090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 18:36:10,287 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 6487530ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:13:05,010 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 2214719ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:27:56,126 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 891111ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:43:06,286 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 910158ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:50:12,393 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 426104ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:52:03,508 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 111106ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 19:53:28,595 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 85078ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 20:34:45,723 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 616670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 22:40:30,199 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 22:46:11,900 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301669ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 22:50:27,909 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 235987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:20:09,649 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 61105ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:25:56,482 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 306819ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:31:38,195 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:37:20,037 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:42:41,783 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301724ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-17 23:54:05,206 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301703ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 00:27:42,316 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 1977091ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:12:44,974 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:18:06,793 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301798ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:23:48,555 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301738ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:29:35,400 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 306824ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:35:17,176 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 01:40:38,934 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301734ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:13:59,980 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 1961025ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:25:23,431 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301693ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:31:05,195 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301746ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:36:46,942 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301728ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:42:28,685 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301720ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 02:47:50,364 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:28:30,776 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 2400391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:34:32,536 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301730ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:39:54,236 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:45:35,946 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301688ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:51:17,689 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301727ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 03:56:40,024 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 302320ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 04:02:21,741 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301699ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 04:38:27,059 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 2125303ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 04:44:08,781 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301701ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 04:49:50,499 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 04:55:32,209 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 05:01:13,891 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301664ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 05:06:35,697 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301795ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 05:48:14,654 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 2117226ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 05:54:56,409 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301709ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:00:38,116 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:06:19,891 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301756ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:12:01,581 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301668ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:17:23,270 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301680ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:23:05,007 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 301717ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 06:35:20,970 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 695949ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 07:44:25,808 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 184133ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 07:46:00,104 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 71163ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 08:07:41,384 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 1301277ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 08:11:47,519 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 246131ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 09:51:43,760 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 5996232ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 19:07:02,860 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 31893676ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 19:22:16,825 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 873927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 19:28:37,676 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 340808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 19:30:04,951 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 87260ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 19:45:48,523 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 943564ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 21:34:57,543 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 6529036ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 21:52:01,178 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 943579ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 21:55:59,330 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 238148ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 22:00:59,641 ERROR 9183 nodejs.ClusterClientNoResponseError: client no response in 60272ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wangjiang/code/yuechen/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 9183
hostname: wangdeMacBook-Pro.local

2020-06-18 23:20:40,536 ERROR 19517 [-/::1/-/18ms POST /api/update_user] nodejs.ReferenceError: onsole is not defined
    at UserController.updateUser (/Users/wangjiang/code/yuechen/app/controller/user.js:57:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 19517
hostname: 192.168.0.115

